export const tableNames = {
  paymentTypes: 'payment_types',
  discounts: 'discounts',
  organizations: 'organizations',
  categories: 'categories',
  items: 'items',
  itemPrices: 'item_prices',
  itemModifiers: 'item_modifiers',
  modifiers: 'modifiers',
  modifierItems: 'modifier_items',
  modifierItemPrices: 'modifier_item_prices',
  priceGroups: 'price_groups',
  printers: 'printers',
  printerGroups: 'printer_groups',
  printerGroupsPrinters: 'printer_groups_printers',
  billPayments: 'bill_payments',
  bills: 'bills',
  billDiscounts: 'bill_discounts',
  billPeriods: 'bill_periods',
  billItems: 'bill_items',
  billItemModifiers: 'bill_item_modifiers',
  billItemModifierItems: 'bill_item_modifier_items',
  billItemPrintLogs: 'bill_item_print_logs',
  billCallLogs: 'bill_call_logs',
  billCallPrintLogs: 'bill_call_print_logs',
  tablePlanElements: 'table_plan_element',
  printCategories: 'print_categories',
} as const;
